name: uncertainty-drivers
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - captum=0.7.0
  - dask-core=2023.11.0
  - ffmpeg=4.3
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipywidgets=8.0.4
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.9
  - lightning-utilities=0.10.0
  - lime=0.2.0.1
  - llvm-openmp=14.0.6
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openjpeg=2.4.0
  - pandas=2.1.4
  - pip=23.3.1
  - py-xgboost=2.0.3
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.2
  - pytorch-lightning=2.1.3
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywavelets=1.5.0
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - shap=0.42.1
  - torchaudio=2.1.2
  - torchmetrics=1.2.1
  - torchvision=0.16.2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - huggingface-hub==0.20.2
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - py-cpuinfo==9.0.0
      - safetensors==0.4.1
      - seaborn==0.13.1
      - thop==0.1.1-2209072238
      - timm==0.8.13.dev0
      - ucimlrepo==0.0.3
      - ultralytics==8.0.124
